### PR TITLE
Update travis.yml with PHP 7.1

### PR DESCRIPTION
**Pull request by DonCallisto**
Added PHP 7.1 to `travis.yml` in order to test the codebase against PHP 7.1

### CODE REVIEW

**Comment by DonCallisto** [comment]
@craue I left out the `@` for silencing the notice as you wrote in https://github.com/craue/CraueFormFlowBundle/pull/290

**Comment by craue** [comment]
The test in question only exists in master, so that's fine. 😏

**Comment by craue** [comment]
Thank you, @DonCallisto.

**Comment by DonCallisto** [comment]
You're very welcome!

**Pull request merged**
