### PR TITLE
fix: merge handled files within collections to correct index

### PR DESCRIPTION
**Pull request by haase-fabian**
Entries inside a collection have numeric keys. Therefore files are appended, which creates new unwanted entries.

[array_merge_recursive](https://www.php.net/manual/en/function.array-merge-recursive.php) appends values to the first array if they have a numeric key.

[array_replace_recursive](https://www.php.net/manual/de/function.array-replace-recursive.php) behaves like array_merge_recursive but replaces numeric keys in the first array.

### CODE REVIEW

**Comment by craue** [comment]
Thanks for your effort. The same fix was already suggested in #276 which still lacks a test or reproducer. It would be great if you could add one here.

**Comment by haase-fabian** [comment]
I added an integration test which closely follows the already existing PhotoUploadTest.

Basically I'm having a collection with one Entity containing an image. The array_merge_recursive function eventually leads to 2 of those entities in the collection. array_replace_recursive keeps the correct count of 1.

The count of the resulting collection is asserted.


Technically the 'allow_add' flag isn't needed, however the array_merge_recursive version generates an error in the form itself, never reaching the third form. To avoid confusion I kept it in.

**Comment by craue** [comment]
Very good!

Would you switch to tabs for indentation? That would avoid me to clutter the history with lots of whitespace changes.

**Comment by craue** [comment]
Thank you very much. I've put your test into #389.

**Pull request closed without merging**
