### PR TITLE
Add support with symfony 5

### PR DESCRIPTION
**Pull request by jderusse**

### CODE REVIEW

**Comment by craue** [comment]
Ah, I already started working on making all of my bundles Symfony 5 compatible. 😄
This PR would still require some adaptations for making it work with all currently supported Symfony versions, so would you mind if we just close it?

**Comment by jderusse** [comment]
I don't mind. I'm looking for a new release of this bundle to migrate my application.
Tell me if you need help. I can update this PR to support early version of the fw

**Comment by craue** [comment]
The master branch is updated. Feel free to try it.
Gonna tag a new release when there are no further issues.

**Comment by jderusse** [comment]
> The master branch is updated. Feel free to try it.

there nothing to review, you commit directly on master without opening a PullRequest.
for instance, I could have told you that you can add a return type hint to a method and still respecting the contract of a method that don't have a return type (the hack in  FormExtensions is not necessary.. moreover `if method_exists(AbstractTypeExtension::class, 'getExtendedTypes'` is true in both version).

**Comment by craue** [comment]
Object return types have been added only in PHP 7.2, but the bundle requires PHP 7.0 currently, so that hack is needed.

**Comment by jderusse** [comment]
then the `if` is wrong... anyway

**Comment by jderusse** [comment]
moreover, it work with PHP 7.0..  https://3v4l.org/1d7CD

**Comment by craue** [comment]
It wouldn't work with PHP 7.0 and Symfony 3.4, though: https://travis-ci.org/craue/CraueFormFlowBundle/jobs/616310798#L320

**Pull request closed without merging**
