### PR TITLE
used Symfony CS for code examples in README.md

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by craue** [comment]
I'm not obeying PSR-2 in my projects. 😏

**Comment by OskarStark** [comment]
> I'm not obeying PSR-2 in my projects. 😏 

I saw this after creating this PR in the code 😄

**Comment by OskarStark** [comment]
... but maybe we should add the types here too?

**Comment by craue** [comment]
I can't see any benefit in this.

**Pull request closed without merging**
