### PR TITLE
Fix bug of setting skipped class to step links 

### PR DESCRIPTION
**Pull request by simohammedhttp**

### CODE REVIEW

**Comment by craue** [comment]
Could you explain the bug in more detail, maybe with an example? I don't see what's wrong with the current implementation. Is it an edge case?

**Comment by simohammedhttp** [comment]
I noticed that when I load the form for the first time all the skippable steps are set with craue_formflow_skipped_step which is weird. 
Let's assume we have a flow of two steps: Step1 and Step2, Step1 contains usedProducts property (collection of checkboxes), Step2 must be skipped if usedProducts != 'ProductX' (the product being studied in survey).
When I load the survey, Step2 is marked skipped, even I haven't responded to Step1 yet.

**Comment by craue** [comment]
The current implementation allows marking succeeding steps as skipped, which is correct. So make sure that your skip function always evaluates to the expected result. Maybe something like this for step 2:
```php
'skip' => function($estimatedCurrentStepNumber, FormFlowInterface $flow) {
	return $estimatedCurrentStepNumber > 1 && !$flow->getFormData()->hasUsedProduct('ProductX');
}
```

**Comment by simohammedhttp** [comment]
Mmm.. Sounds interesting.
It sounds interesting, I'll give it a try.

**Comment by craue** [comment]
@simohammedhttp: Is it ok for you to close this PR?

**Comment by simohammedhttp** [comment]
Yes, I think the actual implementation is quite good.

2015-06-10 13:40 GMT+01:00 Christian Raue <notifications@github.com>:

**Pull request closed without merging**
