### PR TITLE
Use DataManager to check if current flow exists

### PR DESCRIPTION
**Pull request by Warxcell**
Instead of flagging with newInstance = true.

### CODE REVIEW

**Comment by craue** [comment]
Good idea! :+1:

Can you rebase to current master? This should make tests pass.

**Comment by Warxcell** [comment]
Sure, will do later. 

I'm also thinking of restructuring in some way - the problem I have is that I have to make multi step form - without persisting data to session - data will be immediately persisted into it's final location.

The other problem is that user should continue from same step where he left at. I was trying to override instanceId - but without luck so far.

**Comment by craue** [comment]
Thank you, @Warxcell.

> I'm also thinking of restructuring in some way - the problem I have is that I have to make multi step form - without persisting actual data temporary somewhere - data will be immediately persisted into it's final location at each step.

Are you sure this is a good idea?

> The other problem is that user should continue from same step where he left at. For this problem I switched to Doctrine Storage (that's ok) and I was trying to override instanceId (to be same instanceId for same user) - but without luck so far.

This is already in a separate issue, right?

**Comment by Warxcell** [comment]
Yeah, it's in separate PR - you can review the way I think about the things: https://github.com/craue/CraueFormFlowBundle/pull/360 

if you think it's ok - i will continue in that direction.

**Pull request merged**
