### PR TITLE
Allow skipping steps between skipped and noskip

### PR DESCRIPTION
**Pull request by jayesbe**
Take this example. 3 steps. 1st step is not-skipped. 2nd step will be skipped.  The form skips straight to step 3 because the second step is skipped even though the first isnt.

### CODE REVIEW

**Comment by craue** [comment]
I wonder why the tests don't fail after just removing those lines (although some jobs fail due to unrelated deprecation notices). Could you rebase to current master? Quite a lot happened in the last days. :smirk:

And could you provide some failing code for your example or even a failing test?

**Comment by jayesbe** [comment]
How do you rebase using github ?  I don't have the project actually checked out. Made all the edits on github and was just pulling the changes into the dependencies of my project.

I'll see if I can write a test.  Its interesting actually... after tracing the code.. it was kind of obvious that this bit of code was just causing needless loops.

**Comment by craue** [comment]
> How do you rebase using github ?

You cannot.

**Comment by craue** [comment]
@jayesbe, could you make up a failing test yet?

**Comment by craue** [comment]
@jayesbe, since there's no (yet confirmed) bug to be fixed by these code changes, could you open a new PR meant for just removing these (apparently) useless lines?

**Comment by jayesbe** [comment]
sorry man I totally forgot about this. Ill see what I can do.

**Comment by jayesbe** [comment]
https://github.com/craue/CraueFormFlowBundle/pull/243

**Pull request closed without merging**
