### PR TITLE
Updated for php 7 type fixing

### PR DESCRIPTION
**Pull request by garf**
In php 7, there is no scalar type boolean but bool.

### CODE REVIEW

**Comment by craue** [comment]
I've also used `integer` instead of `int` so far. Could you deal with this as well?

**Comment by craue** [comment]
Plus, there are even more occurrences in other files.

**Comment by craue** [comment]
Will you take care of the other files as well?

**Comment by garf** [comment]
Sorry. I didn't have time to do it properly. :(

**Comment by craue** [comment]
Nevertheless, thank you for making us aware of this topic.

**Pull request closed without merging**
