### PR TITLE
fix file upload in collections

### PR DESCRIPTION
**Pull request by jwaschkau**

### CODE REVIEW

**Comment by craue** [comment]
It would be nice to have a test proving that there's an issue at all, as well as proving that this change fixes it, also to avoid future regressions.

**Comment by craue** [comment]
Could you set up such a failing scenario, e.g. by forking [the demo bundle](https://github.com/craue/CraueFormFlowDemoBundle) and modifying the photo upload flow?

**Comment by BlazingSun** [comment]
@craue Yes, i will see what i can do.

**Comment by InTimesIT** [comment]
Hi, I just met this issue.
Thank you for your solution, I've just override the method. :)

**Comment by craue** [comment]
@jwaschkau, any progress?

**Comment by syeikhanugrah** [comment]
This should be merged.

**Comment by craue** [comment]
A test is still needed.

**Comment by craue** [comment]
What exactly is the issue here? Could you explain?

**Comment by craue** [comment]
I can't fix something that's not proven to be broken.

**Comment by jwaschkau** [comment]
Hi @craue,
i won't be able to provide a testcase, because i am not developing PHP anymore.
In some cases the file upload was not working. I think currentStepData was filled with default values and array_merge just appends uploads as a list and does not overwrite existing values.

**Comment by syeikhanugrah** [comment]
@craue I've created repo for this issue: https://github.com/syeikhanugrah/CraueFormFlowBundle276, and try to replace with this: https://gist.github.com/syeikhanugrah/906406e47ec3d763d1fd7d270919e77b. 

I don't know why this happened.

**Comment by blump** [comment]
@syeikhanugrah  's  solution is correct.

Is it possible to correct this problem?

**Comment by craue** [comment]
Unfortunately, the repo @syeikhanugrah mentions is unavailable. We got no test or code exposing the problem and I'm still unable to see the issue. Please enlighten me, @blump.

**Pull request closed without merging**
