### PR TITLE
Add support for Symfony 6.0

### PR DESCRIPTION
**Pull request by jderusse**
:crossed_fingers:

### CODE REVIEW

**Comment by craue** [comment]
Thank you, @jderusse.

**Comment by jderusse** [comment]
Thank you for merging this PR. 

Do you know when you'll have time to tag a new release?

**Comment by craue** [comment]
I wanted to wait until [Travis provides PHP](https://docs.travis-ci.com/user/languages/php#php-versions) 8.1 to run tests against but there's still only "8.1.0" available and I don't want to increase the version manually after a bugfix release.

**Comment by craue** [comment]
Got no response from Travis support in over a week. So I've just tagged **3.6.0** and gonna take care of this later.

**Pull request merged**
