### PR TITLE
added post save current data event

### PR DESCRIPTION
**Pull request by placid2000**
I added an onPostCurrentSaveDataEvent to be able to add some data after saving. Relates to issue #212

### CODE REVIEW

**Comment by craue** [comment]
@placid2000, do you still see a need for this?

**Comment by placid2000** [comment]
Yes ticket can be closed in my opinion since I took another approach.
It'd have just been nice if it was possible to add custom data (for properties that are not set in the form type) to the storage during the process because I end up persisting my the data to the database so this Bundle became kind of obsolete in my implementation I guess. that's a pity ..

**Comment by craue** [comment]
It is possible to use the storage directly.

**Comment by placid2000** [comment]
Ok. I had a very specific case that didn't work. I end up using a workaround like written above.

**Pull request closed without merging**
